# ref: https://github.com/actions/starter-workflows/blob/master/ci/docker-publish.yml
name: build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login docker registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push docker image
        run: |
          docker build . -t ghcr.io/calimaborges/minecraft-bedrock-server/main:${{ github.sha }}
          docker push ghcr.io/calimaborges/minecraft-bedrock-server/main:${{ github.sha }}
